[package]
name = "kukiurldecode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "1.0.0"
serde_urlencoded = "0.6"
serde_json = "1.0"

[[bin]]
name = "kukiurldecode"
path = "main.rs"
